twig:
    default_path: '%kernel.project_dir%/templates'
    debug: '%kernel.debug%'
    strict_variables: '%kernel.debug%'
    paths:
            '%kernel.project_dir%/src/Unit/ex00Bundle/Resources/view': ex00
            '%kernel.project_dir%/src/Unit/ex01Bundle/Resources/view': ex01
